name: Docker Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
